name: 'Do Epic Shit at Xebia'
description: 'Greet someone'
author: 'Xebia'
branding:
  icon: 'alert-circle'
  color: orange
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps:
    - name: Greet the new Xebian
      shell: bash
      env:
        WHO_TO_GREET: ${{ inputs.who-to-greet }}
      run: echo "Hello $WHO_TO_GREET."
    - name: Ascii art logo
      shell: bash 
      run: cat ${{ github.action_path }}/do-epic-shit.txt      
    - name: Send output to the job summary
      shell: bash
      run: |
        echo "What is Epic for you? Discover it at Xebia!" >> $GITHUB_STEP_SUMMARY
        echo "Follow the link: [Do epic shit at Xebia](https://xebia.com/careers/)." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "![Do epic shit logo](https://raw.githubusercontent.com/XpiritBV/doepicshit/main/Xpirit-DoEpicShit-White.jpg)" >> $GITHUB_STEP_SUMMARY
